name: Docker Deploy Workflow

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - dockerTest

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set lowercase repository name
        run: echo "GITHUB_REPOSITORY_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./WebPlayground.Api/Dockerfile
          push: true
          tags: ghcr.io/${{ env.GITHUB_REPOSITORY_LOWERCASE }}:latest